ERROR:django.security.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS. (2019-04-07 22:31:36; exception.py:77)
WARNING:django.request: Bad Request: /api/upload_resume/ (2019-04-07 22:31:36; log.py:228)
INFO:api.views: 1.pdf file with same name already exists (2019-04-25 10:54:30; views.py:89)
INFO:api.views: 1.pdf file with same name already exists (2019-04-25 11:06:06; views.py:89)
INFO:api.views: 1.pdf file with same name already exists (2019-04-25 11:11:12; views.py:89)
INFO:api.views: 1.pdf file with same name already exists (2019-04-25 11:12:01; views.py:89)
INFO:api.views: 1.pdf file with same name already exists (2019-04-25 11:12:44; views.py:89)
INFO:api.views: 1.pdf file with same name already exists (2019-04-25 11:13:33; views.py:89)
INFO:api.views: 1.pdf file with same name already exists (2019-04-25 11:14:13; views.py:89)
INFO:api.views: 1.pdf file with same name already exists (2019-04-25 11:14:29; views.py:89)
INFO:api.views: 1.pdf file with same name already exists (2019-04-25 11:16:52; views.py:89)
INFO:api.views: 1.pdf file with same name already exists (2019-04-25 11:17:33; views.py:89)
INFO:api.views: 1.pdf file with same name already exists (2019-04-25 11:18:57; views.py:89)
ERROR:django.security.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS. (2019-05-07 10:28:05; exception.py:77)
WARNING:django.request: Bad Request: /auth/user (2019-05-07 10:28:05; log.py:228)
WARNING:django.server: "GET /auth/user HTTP/1.1" 400 26 (2019-05-07 10:28:05; basehttp.py:154)
ERROR:django.security.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS. (2019-05-07 10:28:05; exception.py:77)
WARNING:django.request: Bad Request: /favicon.ico (2019-05-07 10:28:05; log.py:228)
WARNING:django.server: "GET /favicon.ico HTTP/1.1" 400 26 (2019-05-07 10:28:05; basehttp.py:154)
ERROR:django.security.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS. (2019-05-07 10:28:08; exception.py:77)
WARNING:django.request: Bad Request: /auth/user/ (2019-05-07 10:28:08; log.py:228)
WARNING:django.server: "GET /auth/user/ HTTP/1.1" 400 26 (2019-05-07 10:28:08; basehttp.py:154)
ERROR:django.security.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS. (2019-05-07 10:28:13; exception.py:77)
WARNING:django.request: Bad Request: /api/auth/user/ (2019-05-07 10:28:13; log.py:228)
WARNING:django.server: "GET /api/auth/user/ HTTP/1.1" 400 26 (2019-05-07 10:28:13; basehttp.py:154)
ERROR:django.security.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS. (2019-05-07 10:28:16; exception.py:77)
WARNING:django.request: Bad Request: /api/auth/user (2019-05-07 10:28:16; log.py:228)
WARNING:django.server: "GET /api/auth/user HTTP/1.1" 400 26 (2019-05-07 10:28:16; basehttp.py:154)
ERROR:django.security.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS. (2019-05-07 10:28:22; exception.py:77)
WARNING:django.request: Bad Request: / (2019-05-07 10:28:22; log.py:228)
WARNING:django.server: "GET / HTTP/1.1" 400 26 (2019-05-07 10:28:22; basehttp.py:154)
ERROR:django.security.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS. (2019-05-08 09:07:08; exception.py:77)
WARNING:django.request: Bad Request: /api/courses/ (2019-05-08 09:07:08; log.py:228)
WARNING:django.server: "OPTIONS /api/courses/ HTTP/1.1" 400 26 (2019-05-08 09:07:08; basehttp.py:154)
ERROR:django.security.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS. (2019-05-08 09:07:37; exception.py:77)
WARNING:django.request: Bad Request: /api/courses/ (2019-05-08 09:07:37; log.py:228)
WARNING:django.server: "OPTIONS /api/courses/ HTTP/1.1" 400 26 (2019-05-08 09:07:37; basehttp.py:154)
